// Alle viktige knapper og felt på siden – én plass å endre
export const $ = sel => document.querySelector(sel);
export const $$ = sel => Array.from(document.querySelectorAll(sel));

export const els = {
  login: $('#login'),
  email: $('#email'),
  password: $('#password'),
  loginBtn: $('#loginBtn'),
  signupBtn: $('#signupBtn'),
  magicBtn: $('#magicBtn'),
  authStatus: $('#auth-status'),
  authError: $('#auth-error'),
  orgnr: $('#orgnr'),
  brregBtn: $('#brregBtn'),
  brregLog: $('#brreg-log'),
  navn: $('#navn'),
  besoksadresse: $('#besoksadresse'),
  besoks_postnr: $('#besoks_postnr'),
  besoks_poststed: $('#besoks_poststed'),
  firma: $('#firma'),
  firma_postadresse: $('#firma_postadresse'),
  firma_postnr: $('#firma_postnr'),
  firma_poststed: $('#firma_poststed'),
  tariffRows: $('#tariff-rows'),
  addRowBtn: $('#addRowBtn'),
  hoyttalere: $('#hoyttalere'),
  kommentar: $('#kommentar'),
  saveDraftBtn: $('#saveDraftBtn'),
  printBtn: $('#printBtn'),
  sendBtn: $('#sendBtn'),
  resetBtn: $('#resetBtn'),
  logoutBtn: $('#logoutBtn'),
  excelFile: $('#excelFile'),
  search: $('#search'),
  zoomMinus: $('#zoomMinus'),
  zoomPlus: $('#zoomPlus'),
  zoomReset: $('#zoomReset'),
  zoomPct: $('#zoomPct'),
  listsDashboard: $('#lists-dashboard'),
  expMonth: $('#expMonth'),
  exportBtn: $('#exportBtn'),
  archive: $('#archive'),
  toast: $('#toast'),
  navButtons: $$('nav button'),
  rowTpl: $('#tariff-row-tpl').content
};